name: portfolio
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  scrollable_positioned_list: ^0.3.8
  lottie: ^3.1.2
  url_launcher: ^6.3.0
  flutter_svg: ^2.0.10+1
  url_strategy: ^0.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  package_info_plus: ^8.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/components/
    - assets/components/contact/
    - assets/components/experience/
    - assets/components/presentation/
    - assets/components/projects/
    - assets/components/social/
    - assets/components/splash/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
  generate: true
